export {
  AGENT_CAPABILITIES,
  type AgentAdapter,
  type AgentCapabilityName,
  type ConformingAgentAdapter,
} from "./agent.js";
export {
  createClaudeAdapter,
  type ClaudeAdapter,
  type ClaudeAdapterOptions,
  type ClaudeCommandInvocation,
  type ClaudeCommandResult,
  type ClaudeCommandRunner,
  type ClaudeConfigureRequest,
  type ClaudeDetectionDetails,
  type ClaudeHookPolicy,
  type ClaudeHookSurface,
  type ClaudeInstallDetails,
  type ClaudeInstallRequest,
  type ClaudeSqueezFeature,
  type SqueezHookSelection,
  type SqueezHookStager,
  type StagedSqueezHooks,
} from "./claude.js";
export {
  PI_EXTENSION_OWNERSHIP_MARKER,
  createPiAdapter,
  type PiAdapter,
  type PiAdapterOptions,
  type PiCommandInvocation,
  type PiCommandResult,
  type PiCommandRunner,
  type PiDetectionDetails,
  type PiInstallDetails,
} from "./pi.js";
export {
  COMPRESSION_ENGINE_CAPABILITIES,
  type CompressionEngineAdapter,
  type CompressionEngineCapabilityName,
} from "./compression-engine.js";
export {
  MINIMUM_SAFE_SQUEEZ_VERSION,
  SQUEEZ_COMPRESSION_CAPABILITIES,
  SQUEEZ_SUPPORTED_HOSTS,
  SQUEEZ_TOOL_OUTPUT_CATEGORIES,
  createSqueezAdapter,
  inspectSqueez,
  squeezEngineState,
  type SqueezAdapterOptions,
  type SqueezCommandResult,
  type SqueezCommandRunner,
  type SqueezDetectionDetails,
} from "./squeez.js";
export {
  LLMTRIM_COMPRESSION_CAPABILITIES,
  createLlmtrimAdapter,
  createLlmtrimPassThroughMeasurement,
  diffLlmtrimTelemetry,
  extractLlmtrimRecallReferences,
  llmtrimEngineState,
  type CreateLlmtrimAdapterOptions,
  type LlmtrimAdapter,
  type LlmtrimCapabilityName,
  type LlmtrimCommandInvocation,
  type LlmtrimCommandResult,
  type LlmtrimCommandRunner,
  type LlmtrimCompressionMeasurement,
  type LlmtrimConfigureRequest,
  type LlmtrimDetectionDetails,
  type LlmtrimHealth,
  type LlmtrimHealthDetails,
  type LlmtrimInstallRequest,
  type LlmtrimPassThroughInput,
  type LlmtrimPreset,
  type LlmtrimRecallReference,
  type LlmtrimTelemetryResult,
  type LlmtrimTelemetrySnapshot,
  type LlmtrimTransportConfiguration,
} from "./llmtrim.js";
export {
  availableCapability,
  degradedCapability,
  unavailableCapability,
  type AdapterContext,
  type AdapterDescriptor,
  type AdapterDetection,
  type AdapterHealth,
  type AdapterHealthStatus,
  type AdapterIssue,
  type AdapterKind,
  type AdapterOperationResult,
  type AdapterVersion,
  type AvailableCapability,
  type CapabilityImportance,
  type CapabilityResult,
  type DegradedCapability,
  type UnavailableCapability,
} from "./shared.js";
